apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: gcr.io/cf-identity-service-oak/spring-auth-server-auth-server:v7
        ports:
        - containerPort: 9000
        env:
        - name: CLIENT_CONFIG
          value: |
            server:
              port: 9000

            logging:
              level:
                root: INFO
                org.springframework.web: INFO
                org.springframework.security: INFO
                org.springframework.security.oauth2: INFO
            #    org.springframework.boot.autoconfigure: DEBUG

            app:
              clients:
                - clientId: "messaging-client"
                  clientSecret: "secret"
                  authenticationMethod: "basic"
                  grant_types:
                    - "authorization_code"
                    - "client_credentials"
                  redirect_uri: "http://35.233.200.29:31592/authorized"
                  scopes:
                    - "message.read"
                    - "message.write"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-server
  template:
    metadata:
      labels:
        app: resource-server
    spec:
      containers:
      - name: resource-server
        image: gcr.io/cf-identity-service-oak/spring-auth-server-resource-server:v2
        ports:
        - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: gcr.io/cf-identity-service-oak/spring-auth-server-client:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30697
    protocol: TCP
  selector:
    app: auth-server
---
apiVersion: v1
kind: Service
metadata:
  name: resource-server-service
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30124
    protocol: TCP
  selector:
    app: resource-server
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31592
    protocol: TCP
  selector:
    app: client
